### PR TITLE
Avoid infinite loop with something like `type_from_bitpix(32)`

### PR DESCRIPTION
**Pull request by emmt**

### CODE REVIEW

**Comment by emmt** [comment]
Sorry I have mixed up the description of the proposed change.  This patch is to avoid an infinite loop with something like `type_from_bitpix(32)` (because `Int` may not be `Cint`).

**Comment by giordano** [comment]
Can you please provide a test?

**Comment by emmt** [comment]
OK that's done.

**Comment by giordano** [comment]
Awesome, thanks!

**Pull request merged**
